name = "command"

[fields.command]
type = "String"

[fields.description]
type = "String"

[fields.intention]
type = "String"

[fields.tool]
type = "String"
multiplicity = "Many"
optional = true

[fields.requireSudo]
type = "Bool"

[fields.deprecated]
type = "Bool"

[fields.topics]
type = "String"
multiplicity = "Many"
optional = true
