name = "command"

[fields.command]
type = "String"

[fields.description]
type = "String"

[fields.topics]
type = "String"
multiplicity = "Many"
optional = true

[fields.legacy]
type = "Bool"
optional = true
