name = "location"

[fields.path]
type = "String"

[fields.partOf]
type = "String"

[fields.type]
type = "Enum"
values = ["directory", "file", "symlink"]

[fields.dirType]
type = "String"
optional = true

[fields.linksToNixPath]
type = "Bool"
optional = true

[fields.topics]
type = "String"
multiplicity = "Many"
optional = true

[fields.description]
type = "String"
